### PR TITLE
adding server functionality, example project and some code improvements

### PR DESCRIPTION
**Pull request by BlackReloaded**
Hi,

i added server functionality for #3, also i added a example project to show how it works

### CODE REVIEW

**Comment by BlackReloaded** [comment]
i have just seen that my commit also fixed #4

**Comment by fajran** [comment]
Hi, sorry for the late response. Thank you for your contribution! I will review it.

**Comment by aneshas** [comment]
Hey guys, do you have plans to merge this any time soon? Thanks.

**Comment by fajran** [comment]
Sorry I have not really had time to properly review this code. But from what I see in the changes, it looks good. My only concern is about the `ProtoBufMessageProvider` class. I imagine there is a name clash possibility, but let's deal it later.

I will merge this change. Sorry for taking so long.

also, thanks for the contribution!

**Comment by aneshas** [comment]
@fajran thank you

**Pull request merged**
